"""
Streamlit Help and Documentation Module
======================================

Help guides, documentation, and user assistance functions extracted from fcf_analysis_streamlit.py.
Provides comprehensive user guidance for the financial analysis application.
"""

# Third-party imports
import streamlit as st


def render_help_guide():
    """Render comprehensive help guide for the application."""
    st.header("📖 Help & Documentation")
    st.write("Welcome to the comprehensive Financial Analysis Application help guide.")
    
    # Add search functionality
    col1, col2 = st.columns([2, 1])
    
    with col1:
        search_query = st.text_input("🔍 Search Help Content:", 
                                   placeholder="e.g., DCF, cash flow, troubleshooting...")
    
    with col2:
        st.write("")  # Empty space for alignment
        search_all = st.checkbox("Search All Content", value=False)
    
    if search_query and search_all:
        st.info(f"🔍 Searching for '{search_query}' across all help sections...")
    
    # Create tabs for different help sections
    help_tabs = st.tabs([
        "🚀 Quick Start",
        "🌍 Multi-Market Support", 
        "📈 FCF Analysis",
        "💰 DCF Valuation",
        "📊 DDM Analysis",
        "📋 P/B Analysis",
        "🗂️ Data Structure",
        "📅 LTM Integration",
        "🏗️ System Architecture",
        "🧮 Mathematical Formulas",
        "⚙️ Configuration",
        "🔧 Troubleshooting",
        "👀 Watch Lists"
    ])
    
    with help_tabs[0]:
        render_quick_start_guide()
    
    with help_tabs[1]:
        render_multi_market_support_guide()
    
    with help_tabs[2]:
        render_fcf_analysis_guide()
    
    with help_tabs[3]:
        render_dcf_valuation_guide()
    
    with help_tabs[4]:
        render_ddm_valuation_guide()
    
    with help_tabs[5]:
        render_pb_analysis_guide()
    
    with help_tabs[6]:
        render_data_structure_guide()
    
    with help_tabs[7]:
        render_ltm_integration_guide()
    
    with help_tabs[8]:
        render_system_architecture_guide()
    
    with help_tabs[9]:
        render_mathematical_formulas_guide()
    
    with help_tabs[10]:
        render_configuration_guide()
    
    with help_tabs[11]:
        render_troubleshooting_guide()
    
    with help_tabs[12]:
        render_watch_lists_guide()


def render_quick_start_guide():
    """Render quick start guide."""
    st.subheader("🚀 Quick Start Guide")
    
    st.write("""
    ### Getting Started in 3 Easy Steps
    
    **Step 1: Load Your Data**
    - Use the sidebar to select your data source (Excel files or API)
    - For Excel: Navigate to your company's financial folder
    - For API: Enter a ticker symbol (e.g., AAPL, MSFT)
    
    **Step 2: Choose Your Analysis**
    - **FCF Analysis**: Free Cash Flow trends and projections
    - **DCF Valuation**: Discounted Cash Flow company valuation
    - **DDM Analysis**: Dividend Discount Model for dividend-paying stocks
    - **P/B Analysis**: Advanced Price-to-Book analysis with statistical methods and quality assessment
    
    **Step 3: Generate Reports**
    - View interactive charts and tables
    - Export results to Excel or CSV
    - Save reports for future reference
    """)
    
    st.info("💡 **Pro Tip**: Start with FCF Analysis to understand cash flow patterns, then proceed to DCF for valuation.")


def render_multi_market_support_guide():
    """Render multi-market support guide."""
    st.subheader("🌍 Multi-Market Support")
    
    st.write("""
    ### Supported Markets
    
    **US Markets**
    - NYSE, NASDAQ stocks
    - Standard ticker symbols (AAPL, MSFT, GOOGL)
    - USD currency reporting
    
    **TASE (Tel Aviv Stock Exchange)**
    - Israeli stocks with .TA suffix
    - ILS (Shekel) currency support
    - Local accounting standards adaptation
    
    ### Market Selection
    1. Choose market from dropdown in sidebar
    2. Enter ticker with or without suffix
    3. System automatically formats for selected market
    
    ### Currency Handling
    - Automatic currency detection
    - Multi-currency analysis support
    - Exchange rate considerations in valuations
    """)


def render_fcf_analysis_guide():
    """Render FCF analysis guide."""
    st.subheader("📈 Free Cash Flow Analysis Guide")
    
    st.write("""
    ### Understanding Free Cash Flow
    
    **What is FCF?**
    Free Cash Flow represents the cash generated by operations after capital expenditures.
    It's a key indicator of financial health and growth sustainability.
    
    **FCF Types Supported:**
    - **FCFE (Free Cash Flow to Equity)**: Available to equity holders
    - **FCFF (Free Cash Flow to Firm)**: Available to all capital providers
    - **Levered FCF**: Cash flow after debt service
    
    ### Key Metrics Displayed:
    - Historical FCF trends (5+ years)
    - Growth rates (YoY, CAGR)
    - FCF margins and efficiency ratios
    - Capital allocation analysis
    
    ### Interpretation Tips:
    - ✅ **Positive, Growing FCF**: Strong financial position
    - ⚠️ **Declining FCF**: May indicate business challenges
    - 📊 **Volatile FCF**: Check for cyclical patterns or one-time items
    """)


def render_dcf_valuation_guide():
    """Render DCF valuation guide."""
    st.subheader("💰 DCF Valuation Guide")
    
    st.write("""
    ### Discounted Cash Flow Model
    
    **Purpose:**
    Estimate intrinsic company value by discounting future cash flows to present value.
    
    **Key Components:**
    1. **Historical FCF**: Base for projections
    2. **Growth Assumptions**: Revenue and FCF growth rates
    3. **Terminal Value**: Long-term value assumption
    4. **Discount Rate**: Risk-adjusted required return (WACC)
    
    ### Model Parameters:
    - **Projection Period**: Typically 5-10 years
    - **Terminal Growth Rate**: Long-term sustainable growth (2-4%)
    - **Discount Rate**: Company's weighted average cost of capital
    
    ### Output Interpretation:
    - **Enterprise Value**: Total company value
    - **Equity Value**: Value attributable to shareholders
    - **Price per Share**: Estimated fair value per share
    - **Sensitivity Analysis**: Value ranges based on assumption changes
    """)


def render_ddm_valuation_guide():
    """Render DDM valuation guide."""
    st.subheader("📊 Dividend Discount Model Guide")
    
    st.write("""
    ### Dividend Discount Model (DDM)
    
    **Best For:**
    - Dividend-paying companies
    - Stable, mature businesses
    - Utilities, REITs, consumer staples
    
    **Model Variants:**
    - **Gordon Growth Model**: Constant dividend growth
    - **Multi-Stage DDM**: Varying growth phases
    - **Zero Growth Model**: Stable dividend assumption
    
    ### Key Inputs:
    - Historical dividend payments
    - Expected dividend growth rate
    - Required rate of return (cost of equity)
    
    ### Limitations:**
    - Not suitable for non-dividend paying stocks
    - Sensitive to growth rate assumptions
    - May not capture full company value
    """)


def render_pb_analysis_guide():
    """Render P/B analysis guide."""
    st.subheader("📋 Price-to-Book Analysis Guide")
    
    # Create sub-tabs for detailed P/B methodology
    pb_tabs = st.tabs([
        "📊 Overview",
        "🔬 Methodology",
        "📈 Data Sources",
        "🧮 Calculations",
        "📊 Quality Assessment",
        "💡 Interpretation"
    ])
    
    with pb_tabs[0]:
        st.write("""
        ### Price-to-Book Ratio Analysis
        
        **What is P/B Ratio?**
        Price-to-Book compares market price to book value per share.
        Useful for value investing and asset-heavy businesses.
        
        **Analysis Features:**
        - Historical P/B trends with statistical analysis
        - Industry comparisons and benchmarking
        - Statistical fair value estimation using multiple methods
        - Confidence intervals and risk scenarios
        - Quality assessment and data validation
        
        ### Key Benefits:
        - **Multi-source Data Integration**: Combines Excel and API sources
        - **Advanced Statistical Analysis**: Uses IQR outlier detection and Monte Carlo simulation
        - **Quality-Weighted Results**: Adjusts calculations based on data reliability
        - **Risk Assessment**: Provides Bear/Base/Bull scenarios
        """)
    
    with pb_tabs[1]:
        st.write("""
        ### Calculation Methodology
        
        Our P/B analysis employs a sophisticated multi-step process:
        
        #### 1. Data Collection & Normalization
        - Retrieves historical price data from multiple sources
        - Extracts balance sheet data (quarterly/annual statements)
        - Normalizes data formats across different providers
        - Validates data completeness and consistency
        
        #### 2. Temporal Data Alignment
        - **Advanced Matching Algorithm**: Finds the most recent balance sheet date before each price point
        - **Quarterly Reporting Cycle**: Accounts for ~90-day reporting intervals
        - **Data Quality Weighting**: Higher weights for more recent and complete data
        
        #### 3. Historical P/B Calculation
        - Calculates Book Value per Share for each period
        - Computes P/B ratios using aligned price and fundamental data  
        - Applies quality weighting based on data reliability
        
        #### 4. Statistical Analysis
        - **Outlier Detection**: Uses IQR method (Q1 - 1.5×IQR to Q3 + 1.5×IQR)
        - **Comprehensive Statistics**: Mean, median, percentiles, rolling averages
        - **Trend Analysis**: Linear regression and autocorrelation testing
        - **Monte Carlo Simulation**: 1,000-10,000 samples for robust fair value distribution
        """)
    
    with pb_tabs[2]:
        st.write("""
        ### Data Sourcing Strategy
        
        #### Primary Method: Excel-Based Annual Data
        **Advantages:**
        - Complete annual financial statements
        - Higher data quality and consistency  
        - Manual data validation and cleaning
        - Reduced API rate limit constraints
        
        **Structure:**
        - `data/companies/{TICKER}/FY/Balance Sheet.xlsx`
        - Historical price data from APIs
        
        #### Fallback Method: API-Based Data
        **Sources:**
        - **Yahoo Finance**: Primary for price data and basic fundamentals
        - **Alpha Vantage**: Comprehensive quarterly financial data
        - **Financial Modeling Prep**: Professional-grade financial data  
        - **Polygon.io**: High-quality market data and fundamentals
        
        #### Multi-Source Integration
        - **Weighted Averaging**: Based on data quality scores
        - **Cross-Validation**: Comparing values across sources
        - **Quality Assessment**: Prioritizing higher-quality data sources
        """)
    
    with pb_tabs[3]:
        st.write("""
        ### Core Calculations
        
        #### Basic P/B Ratio Formula
        ```
        P/B Ratio = Stock Price / Book Value per Share
        
        Where:
        Book Value per Share = Total Shareholders' Equity / Shares Outstanding
        ```
        
        #### Field Mapping Across Sources
        **Shareholders' Equity:**
        - Alpha Vantage: `totalStockholderEquity`, `stockholderEquity`
        - Financial Modeling Prep: `totalStockholdersEquity`
        - Polygon: `equity`, `stockholders_equity`
        - yfinance: `Total Stockholder Equity`
        
        **Shares Outstanding:**
        - `commonSharesOutstanding`, `sharesOutstanding`
        - `weightedAverageShsOut`, `impliedSharesOutstanding`
        
        #### Fair Value Estimation
        ```
        Fair Value = Quality-Weighted Mean P/B × Current Book Value per Share
        ```
        
        **Confidence Intervals:**
        - Quality-adjusted confidence levels
        - Statistical and Monte Carlo-based margins
        - Multiple confidence levels (80%, 90%, 95%, 99%)
        """)
    
    with pb_tabs[4]:
        st.write("""
        ### Quality Assessment Framework
        
        #### Data Quality Metrics
        - **P/B Data Completeness**: Percentage of periods with valid P/B calculations
        - **Price Data Quality**: Assessment of historical price data continuity
        - **Balance Sheet Quality**: Evaluation of fundamental data completeness
        - **Temporal Consistency**: Regularity of reporting intervals
        - **Outlier Detection Score**: Percentage of reasonable data points
        
        #### Overall Quality Score Calculation
        ```
        Quality Score = (
            completeness × 0.20 +
            accuracy × 0.20 +
            timeliness × 0.10 +
            consistency × 0.15 +
            pb_data_completeness × 0.15 +
            price_data_quality × 0.10 +
            balance_sheet_quality × 0.10
        ) × (1.0 - data_gap_penalty)
        ```
        
        #### Quality Interpretation
        - **High Quality (>0.8)**: Strong confidence, suitable for investment decisions
        - **Medium Quality (0.5-0.8)**: Reasonable confidence, consider additional validation
        - **Low Quality (<0.5)**: Limited confidence, use results cautiously
        """)
    
    with pb_tabs[5]:
        st.write("""
        ### Interpretation & Usage
        
        #### P/B Ratio Guidelines
        - **P/B < 1**: Potentially undervalued (or distressed situation)
        - **P/B 1-2**: Reasonable valuation for stable businesses
        - **P/B > 3**: May be overvalued (or high-growth company)
        - **Industry Context**: Always compare to sector averages
        
        #### Risk Scenarios
        **Bear Scenario (15% probability):**
        - P/B = Mean - 2 × Standard Deviation
        - Downside risk assessment
        
        **Base Scenario (70% probability):**
        - P/B = Quality-weighted historical mean
        - Most likely valuation outcome
        
        **Bull Scenario (15% probability):**
        - P/B = Mean + 2 × Standard Deviation  
        - Upside potential assessment
        
        #### Best Use Cases
        - **Banks and Financial Institutions**: Asset-heavy business models
        - **Real Estate Companies**: Book value closely tied to market value
        - **Manufacturing and Industrial Firms**: Significant fixed asset base
        - **Value Investing Strategies**: Identifying undervalued opportunities
        - **Distressed Situations**: When earnings-based models may not apply
        
        #### Limitations to Consider
        - May not capture intangible asset value (brands, IP, goodwill)
        - Less suitable for asset-light technology companies
        - Book value can be affected by accounting treatments
        - Historical P/B may not reflect current market conditions
        """)
        
        st.info("💡 **Pro Tip**: Use P/B analysis alongside other valuation methods (DCF, DDM) for comprehensive investment analysis. Pay special attention to the quality score and data completeness warnings.")
        
        # Link to detailed technical documentation
        st.write("---")
        st.write("📖 **For Technical Details**: See `docs/PB_HISTORICAL_METHODOLOGY.md` for complete mathematical formulas, algorithm details, and implementation specifics.")


def render_data_structure_guide():
    """Render data structure guide."""
    st.subheader("🗂️ Data Structure Guide")
    
    st.write("""
    ### Excel File Organization
    
    **Required Structure:**
    ```
    Company_Folder/
    ├── FY2023/
    │   ├── Income_Statement.xlsx
    │   ├── Balance_Sheet.xlsx
    │   └── Cash_Flow.xlsx
    ├── FY2022/
    └── LTM/ (optional)
    ```
    
    **File Naming:**
    - Use consistent naming across years
    - Include statement type in filename
    - Supported formats: .xlsx, .xls
    
    ### API Data Sources:
    - **Yahoo Finance**: Free, comprehensive data
    - **Financial Modeling Prep**: Professional-grade data
    - **Alpha Vantage**: Alternative data provider
    - **Polygon**: Market data specialist
    
    ### Technical Documentation:
    - **P/B Methodology**: See P/B Analysis tab for detailed calculation algorithms
    - **Implementation Details**: `docs/PB_HISTORICAL_METHODOLOGY.md`
    - **Mathematical Formulas**: See Mathematical Formulas tab
    """)


def render_ltm_integration_guide():
    """Render LTM integration guide."""
    st.subheader("📅 Last Twelve Months (LTM) Integration")
    
    st.write("""
    ### LTM Data Support
    
    **Purpose:**
    Incorporate most recent 12-month financial data for current analysis.
    
    **Implementation:**
    - Separate LTM folder in company directory
    - Automatic detection and integration
    - Blends with annual historical data
    
    **Benefits:**
    - More current financial picture
    - Better trend analysis
    - Improved valuation accuracy
    
    **Setup:**
    1. Create 'LTM' folder in company directory
    2. Add latest quarterly/LTM financial statements
    3. System automatically detects and integrates
    """)


def render_system_architecture_guide():
    """Render system architecture guide."""
    st.subheader("🏗️ System Architecture")
    
    st.write("""
    ### Application Components
    
    **Core Modules:**
    - `FinancialCalculator`: Central calculation engine
    - `DCFValuator`: Discounted cash flow modeling
    - `DDMValuator`: Dividend discount modeling
    - `PBCalculationEngine`: Advanced P/B ratio calculations with temporal matching
    - `PBHistoricalAnalysisEngine`: Comprehensive P/B trend analysis and statistics
    - `DataProcessor`: Data loading and validation
    - `UniversalDataRegistry`: Configuration-driven data management
    
    **Data Sources:**
    - Excel file processing
    - Multiple API integrations
    - Real-time market data
    - Cached data management
    
    **User Interface:**
    - Streamlit-based web interface
    - Interactive charts and tables
    - Export and reporting capabilities
    - Configuration management
    """)


def render_mathematical_formulas_guide():
    """Render mathematical formulas guide."""
    st.subheader("🧮 Mathematical Formulas")
    
    st.write("""
    ### Core Financial Formulas
    
    **Free Cash Flow:**
    ```
    FCF = Operating Cash Flow - Capital Expenditures
    FCFE = FCF - Net Debt Issued
    FCFF = FCF + Interest × (1 - Tax Rate)
    ```
    
    **DCF Valuation:**
    ```
    PV = FCF₁/(1+r)¹ + FCF₂/(1+r)² + ... + Terminal Value/(1+r)ⁿ
    Terminal Value = FCFₙ × (1+g) / (r-g)
    ```
    
    **DDM Valuation:**
    ```
    Gordon Growth: P₀ = D₁/(r-g)
    Multi-Stage: P₀ = Σ[Dₜ/(1+r)ᵗ] + Pₙ/(1+r)ⁿ
    ```
    
    **P/B Analysis:**
    ```
    P/B Ratio = Market Price / Book Value per Share
    Book Value per Share = Total Shareholders' Equity / Shares Outstanding
    Fair Value = Quality-Weighted Mean P/B × Current Book Value per Share
    
    Quality Score = (
        completeness × 0.20 + accuracy × 0.20 + timeliness × 0.10 +
        consistency × 0.15 + pb_data_completeness × 0.15 +
        price_data_quality × 0.10 + balance_sheet_quality × 0.10
    ) × (1.0 - data_gap_penalty)
    
    Outlier Detection: IQR Method
    Lower Bound = Q1 - 1.5 × IQR
    Upper Bound = Q3 + 1.5 × IQR
    ```
    
    💡 **See P/B Analysis tab for detailed methodology and implementation specifics**
    """)


def render_configuration_guide():
    """Render configuration guide."""
    st.subheader("⚙️ Configuration Guide")
    
    st.write("""
    ### Application Settings
    
    **Data Source Preferences:**
    - Primary API source selection
    - Fallback source configuration
    - Data refresh intervals
    
    **Calculation Parameters:**
    - Default growth rate assumptions
    - Risk-free rate sources
    - Industry-specific adjustments
    
    **Display Options:**
    - Currency preferences
    - Number formatting
    - Chart styling
    
    **Export Settings:**
    - Default output directories
    - File naming conventions
    - Format preferences
    """)


def render_troubleshooting_guide():
    """Render troubleshooting guide."""
    st.subheader("🔧 Troubleshooting Guide")
    
    st.write("""
    ### Common Issues & Solutions
    
    **Data Loading Problems:**
    - ❌ "No data found" → Check file structure and naming
    - ❌ "API timeout" → Try different data source
    - ❌ "Invalid ticker" → Verify symbol and market selection
    
    **Calculation Errors:**
    - ❌ "Missing FCF data" → Check cash flow statement completeness
    - ❌ "Negative growth rates" → Review historical data accuracy
    - ❌ "Unrealistic valuations" → Verify input assumptions
    
    **Performance Issues:**
    - 🐌 Slow loading → Clear browser cache
    - 🐌 Chart rendering → Reduce data range
    - 🐌 Export delays → Check available disk space
    
    **Getting Help:**
    - Check error messages for specific guidance
    - Review data quality warnings
    - Consult documentation for parameter meanings
    """)


def render_watch_lists_guide():
    """Render watch lists guide."""
    st.subheader("👀 Watch Lists Guide")
    
    st.write("""
    ### Portfolio Monitoring
    
    **Features:**
    - Create custom watch lists
    - Track multiple companies
    - Compare key metrics
    - Monitor valuation changes
    
    **Setup Process:**
    1. Navigate to Watch Lists tab
    2. Create new watch list
    3. Add companies by ticker or folder
    4. Configure monitoring parameters
    
    **Analysis Options:**
    - Side-by-side metric comparison
    - Relative valuation analysis
    - Trend monitoring
    - Alert configuration
    
    **Best Practices:**
    - Group similar companies (sector, market cap)
    - Regular monitoring schedule
    - Document investment thesis
    - Track assumption changes
    """)