"""
Standard Financial Variables Schema
===================================

This module defines a comprehensive catalog of 100+ standard financial variables used across
the investment analysis platform. Each variable includes complete metadata, validation rules,
data types, units, and source-specific aliases to ensure data consistency and enable 
variable-driven processing workflows.

The schema builds on the existing FinancialVariableRegistry system and provides pre-defined
variables covering:

1. Core Financials: Revenue, Net Income, Total Assets, Shareholders Equity, etc.
2. Cash Flow: Operating CF, Free Cash Flow variants (FCFF, FCFE, LFCF), CapEx
3. Market Data: Stock Price, Market Cap, Shares Outstanding, Beta, P/E, P/B ratios
4. Calculated Metrics: ROE, ROA, ROIC, Debt ratios, Growth rates  
5. DCF Components: WACC, Terminal Value, Discount Rate
6. Balance Sheet Details: Current Assets, Current Liabilities, Working Capital
7. Income Statement Details: Gross Profit, Operating Income, EBITDA
8. Valuation Ratios: EV/Revenue, EV/EBITDA, PEG Ratio
9. Efficiency Metrics: Asset Turnover, Receivables Turnover
10. Per-Share Metrics: EPS, Book Value per Share, Dividend per Share

Usage Example:
--------------
>>> from standard_financial_variables import get_standard_variables, register_all_variables
>>> from core.data_processing.financial_variable_registry import get_registry
>>>
>>> # Register all standard variables
>>> registry = get_registry()
>>> register_all_variables(registry)
>>> 
>>> # Get all revenue-related variables
>>> revenue_vars = [v for v in get_standard_variables() if 'revenue' in v.tags]
>>> print(f"Found {len(revenue_vars)} revenue-related variables")
"""

from typing import List, Dict, Any
from datetime import datetime

from .financial_variable_registry import (
    VariableDefinition,
    VariableCategory, 
    DataType,
    Units,
    ValidationRule,
    FinancialVariableRegistry
)


def get_income_statement_variables() -> List[VariableDefinition]:
    """Define all Income Statement variables with complete metadata"""
    variables = []
    
    # Core Revenue Variables
    variables.extend([
        VariableDefinition(
            name="revenue",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total company revenue/net sales",
            long_description="Total amount of income generated by the sale of goods or services related to the company's primary operations",
            calculation_method="Sum of all revenue streams from core business operations",
            aliases={
                "excel": "Revenue",
                "yfinance": "totalRevenue", 
                "fmp": "revenue",
                "alpha_vantage": "totalRevenue",
                "polygon": "revenues"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Revenue cannot be negative"),
                ValidationRule("range", parameters={"min": 0, "max": 1000000}, warning_only=True)
            ],
            tags={"core", "income_statement", "fundamental", "revenue"},
            required=True
        ),
        
        VariableDefinition(
            name="total_revenue",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total revenue (alias for revenue)",
            aliases={
                "excel": "Total Revenue",
                "yfinance": "totalRevenue",
                "fmp": "totalRevenue"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Total revenue cannot be negative")
            ],
            tags={"core", "income_statement", "revenue", "alias"},
            derived_from=["revenue"]
        ),
        
        VariableDefinition(
            name="gross_revenue", 
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Gross revenue before returns and allowances",
            aliases={
                "excel": "Gross Revenue",
                "fmp": "grossRevenue"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Gross revenue cannot be negative")
            ],
            tags={"income_statement", "revenue", "gross"}
        )
    ])
    
    # Cost and Profit Variables
    variables.extend([
        VariableDefinition(
            name="cost_of_revenue",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Direct costs associated with producing revenue",
            aliases={
                "excel": "Cost of Revenue",
                "yfinance": "costOfRevenue",
                "fmp": "costOfRevenue",
                "alpha_vantage": "costOfRevenue"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Cost of revenue cannot be negative")
            ],
            tags={"income_statement", "costs", "cogs"}
        ),
        
        VariableDefinition(
            name="gross_profit",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Revenue minus cost of goods sold",
            calculation_method="Revenue - Cost of Revenue",
            aliases={
                "excel": "Gross Profit",
                "yfinance": "grossProfit", 
                "fmp": "grossProfit",
                "alpha_vantage": "grossProfit"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50000, "max": 500000}, warning_only=True)
            ],
            tags={"core", "income_statement", "profitability", "gross"},
            depends_on=["revenue", "cost_of_revenue"]
        ),
        
        VariableDefinition(
            name="operating_income",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Operating income/EBIT before interest and taxes",
            long_description="Earnings from core business operations excluding interest income/expense and tax expenses",
            calculation_method="Gross Profit - Operating Expenses",
            aliases={
                "excel": "Operating Income",
                "yfinance": "operatingIncome",
                "fmp": "operatingIncome", 
                "alpha_vantage": "operatingIncome"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -100000, "max": 200000}, warning_only=True)
            ],
            tags={"core", "income_statement", "profitability", "operating", "ebit"},
            required=True
        ),
        
        VariableDefinition(
            name="ebit",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Earnings Before Interest and Taxes",
            aliases={
                "excel": "EBIT",
                "yfinance": "ebit",
                "fmp": "ebit"
            },
            tags={"core", "income_statement", "profitability", "ebit"},
            derived_from=["operating_income"]
        ),
        
        VariableDefinition(
            name="ebitda",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Earnings Before Interest, Taxes, Depreciation, and Amortization",
            calculation_method="EBIT + Depreciation + Amortization",
            aliases={
                "excel": "EBITDA",
                "yfinance": "ebitda",
                "fmp": "ebitda"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50000, "max": 300000}, warning_only=True)
            ],
            tags={"core", "income_statement", "profitability", "ebitda", "non_gaap"},
            depends_on=["ebit", "depreciation_amortization"]
        ),
        
        VariableDefinition(
            name="net_income",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Net income/earnings after all expenses and taxes",
            long_description="Company's total earnings/profit after accounting for all revenue and expenses including taxes and interest",
            aliases={
                "excel": "Net Income",
                "yfinance": "netIncome",
                "fmp": "netIncome",
                "alpha_vantage": "netIncome"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50000, "max": 150000}, warning_only=True)
            ],
            tags={"core", "income_statement", "profitability", "bottom_line"},
            required=True
        )
    ])
    
    # Expense Variables
    variables.extend([
        VariableDefinition(
            name="operating_expenses",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total operating expenses",
            aliases={
                "excel": "Operating Expenses",
                "yfinance": "operatingExpense",
                "fmp": "operatingExpenses"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Operating expenses should be positive")
            ],
            tags={"income_statement", "expenses", "operating"}
        ),
        
        VariableDefinition(
            name="research_development",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Research and development expenses",
            aliases={
                "excel": "R&D",
                "yfinance": "researchDevelopment",
                "fmp": "researchAndDevelopmentExpenses"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="R&D expenses cannot be negative")
            ],
            tags={"income_statement", "expenses", "rd", "innovation"}
        ),
        
        VariableDefinition(
            name="selling_general_admin",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Selling, General & Administrative expenses",
            aliases={
                "excel": "SG&A",
                "yfinance": "sellingGeneralAdministrative", 
                "fmp": "sellingGeneralAndAdministrativeExpenses"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="SG&A expenses should be positive")
            ],
            tags={"income_statement", "expenses", "sga"}
        ),
        
        VariableDefinition(
            name="interest_expense",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Interest expense on debt",
            aliases={
                "excel": "Interest Expense",
                "yfinance": "interestExpense",
                "fmp": "interestExpense"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Interest expense should be positive")
            ],
            tags={"income_statement", "expenses", "interest", "debt"}
        ),
        
        VariableDefinition(
            name="tax_expense",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Income tax expense", 
            aliases={
                "excel": "Tax Expense",
                "yfinance": "incomeTaxExpense",
                "fmp": "incomeTaxExpense"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Tax expense should be positive")
            ],
            tags={"income_statement", "expenses", "tax"}
        )
    ])
    
    # Per-Share Variables
    variables.extend([
        VariableDefinition(
            name="earnings_per_share",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.FLOAT,
            units=Units.DOLLARS,
            description="Basic earnings per share",
            calculation_method="Net Income / Weighted Average Shares Outstanding",
            aliases={
                "excel": "EPS",
                "yfinance": "basicEPS",
                "fmp": "eps"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50, "max": 100}, warning_only=True)
            ],
            tags={"core", "income_statement", "per_share", "eps", "profitability"},
            depends_on=["net_income", "weighted_avg_shares"]
        ),
        
        VariableDefinition(
            name="diluted_eps",
            category=VariableCategory.INCOME_STATEMENT,
            data_type=DataType.FLOAT,
            units=Units.DOLLARS,
            description="Diluted earnings per share",
            aliases={
                "excel": "Diluted EPS",
                "yfinance": "dilutedEPS",
                "fmp": "epsdiluted"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50, "max": 100}, warning_only=True)
            ],
            tags={"core", "income_statement", "per_share", "eps", "diluted"}
        )
    ])
    
    return variables


def get_balance_sheet_variables() -> List[VariableDefinition]:
    """Define all Balance Sheet variables"""
    variables = []
    
    # Asset Variables
    variables.extend([
        VariableDefinition(
            name="total_assets",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total assets on balance sheet",
            aliases={
                "excel": "Total Assets",
                "yfinance": "totalAssets",
                "fmp": "totalAssets",
                "alpha_vantage": "totalAssets"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Total assets must be positive")
            ],
            tags={"core", "balance_sheet", "assets", "fundamental"},
            required=True
        ),
        
        VariableDefinition(
            name="current_assets",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Current assets (liquid within one year)",
            aliases={
                "excel": "Current Assets",
                "yfinance": "totalCurrentAssets",
                "fmp": "totalCurrentAssets"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Current assets cannot be negative")
            ],
            tags={"balance_sheet", "assets", "current", "liquidity"}
        ),
        
        VariableDefinition(
            name="cash_and_equivalents",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Cash and cash equivalents",
            aliases={
                "excel": "Cash and Cash Equivalents",
                "yfinance": "cash",
                "fmp": "cashAndCashEquivalents"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Cash cannot be negative")
            ],
            tags={"core", "balance_sheet", "assets", "cash", "liquidity"}
        ),
        
        VariableDefinition(
            name="accounts_receivable",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Accounts receivable",
            aliases={
                "excel": "Accounts Receivable",
                "yfinance": "netReceivables",
                "fmp": "netReceivables"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Receivables cannot be negative")
            ],
            tags={"balance_sheet", "assets", "current", "receivables"}
        ),
        
        VariableDefinition(
            name="inventory",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Inventory value",
            aliases={
                "excel": "Inventory",
                "yfinance": "inventory",
                "fmp": "inventory"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Inventory cannot be negative")
            ],
            tags={"balance_sheet", "assets", "current", "inventory"}
        ),
        
        VariableDefinition(
            name="property_plant_equipment",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Property, Plant & Equipment (net)",
            aliases={
                "excel": "PP&E",
                "yfinance": "propertyPlantEquipment",
                "fmp": "propertyPlantEquipmentNet"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="PP&E cannot be negative")
            ],
            tags={"balance_sheet", "assets", "fixed", "ppe"}
        )
    ])
    
    # Liability Variables
    variables.extend([
        VariableDefinition(
            name="total_liabilities",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total liabilities",
            aliases={
                "excel": "Total Liabilities",
                "yfinance": "totalLiab",
                "fmp": "totalLiabilities",
                "alpha_vantage": "totalLiabilities"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Total liabilities cannot be negative")
            ],
            tags={"core", "balance_sheet", "liabilities"}
        ),
        
        VariableDefinition(
            name="current_liabilities",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Current liabilities (due within one year)",
            aliases={
                "excel": "Current Liabilities",
                "yfinance": "totalCurrentLiabilities",
                "fmp": "totalCurrentLiabilities"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Current liabilities cannot be negative")
            ],
            tags={"balance_sheet", "liabilities", "current"}
        ),
        
        VariableDefinition(
            name="total_debt",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total debt (short-term + long-term)",
            calculation_method="Short Term Debt + Long Term Debt",
            aliases={
                "excel": "Total Debt",
                "yfinance": "totalDebt",
                "fmp": "totalDebt"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Total debt cannot be negative")
            ],
            tags={"core", "balance_sheet", "liabilities", "debt"},
            depends_on=["short_term_debt", "long_term_debt"]
        ),
        
        VariableDefinition(
            name="long_term_debt",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Long-term debt",
            aliases={
                "excel": "Long Term Debt",
                "yfinance": "longTermDebt",
                "fmp": "longTermDebt"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Long-term debt cannot be negative")
            ],
            tags={"balance_sheet", "liabilities", "debt", "long_term"}
        ),
        
        VariableDefinition(
            name="short_term_debt",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Short-term debt",
            aliases={
                "excel": "Short Term Debt",
                "yfinance": "shortTermDebt",
                "fmp": "shortTermDebt"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Short-term debt cannot be negative")
            ],
            tags={"balance_sheet", "liabilities", "debt", "short_term"}
        )
    ])
    
    # Equity Variables
    variables.extend([
        VariableDefinition(
            name="shareholders_equity",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total shareholders' equity",
            calculation_method="Total Assets - Total Liabilities",
            aliases={
                "excel": "Shareholders Equity",
                "yfinance": "totalStockholderEquity",
                "fmp": "totalStockholdersEquity"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -10000, "max": 500000}, warning_only=True)
            ],
            tags={"core", "balance_sheet", "equity"},
            depends_on=["total_assets", "total_liabilities"],
            required=True
        ),
        
        VariableDefinition(
            name="retained_earnings",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Retained earnings",
            aliases={
                "excel": "Retained Earnings",
                "yfinance": "retainedEarnings",
                "fmp": "retainedEarnings"
            },
            tags={"balance_sheet", "equity", "retained"}
        ),
        
        VariableDefinition(
            name="book_value",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Total book value (same as shareholders equity)",
            aliases={
                "excel": "Book Value",
                "yfinance": "bookValue",
                "fmp": "bookValue"
            },
            tags={"balance_sheet", "equity", "book_value", "valuation"},
            derived_from=["shareholders_equity"]
        ),
        
        VariableDefinition(
            name="tangible_book_value",
            category=VariableCategory.BALANCE_SHEET,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Tangible book value (excluding intangibles)",
            calculation_method="Book Value - Intangible Assets",
            aliases={
                "excel": "Tangible Book Value",
                "fmp": "tangibleBookValue"
            },
            tags={"balance_sheet", "equity", "tangible", "valuation"},
            depends_on=["book_value", "intangible_assets"]
        )
    ])
    
    # Calculated Balance Sheet Metrics
    variables.extend([
        VariableDefinition(
            name="working_capital",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Working capital",
            calculation_method="Current Assets - Current Liabilities",
            aliases={
                "excel": "Working Capital",
                "fmp": "workingCapital"
            },
            tags={"calculated", "balance_sheet", "working_capital", "liquidity"},
            depends_on=["current_assets", "current_liabilities"]
        ),
        
        VariableDefinition(
            name="net_debt",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Net debt",
            calculation_method="Total Debt - Cash and Cash Equivalents",
            aliases={
                "excel": "Net Debt",
                "fmp": "netDebt"
            },
            tags={"calculated", "balance_sheet", "debt", "net_debt"},
            depends_on=["total_debt", "cash_and_equivalents"]
        )
    ])
    
    return variables


def get_cash_flow_variables() -> List[VariableDefinition]:
    """Define all Cash Flow Statement variables"""
    variables = []
    
    # Operating Cash Flow Variables
    variables.extend([
        VariableDefinition(
            name="operating_cash_flow",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Cash flow from operating activities",
            aliases={
                "excel": "Operating Cash Flow",
                "yfinance": "operatingCashFlow",
                "fmp": "operatingCashFlow",
                "alpha_vantage": "operatingCashFlow"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50000, "max": 200000}, warning_only=True)
            ],
            tags={"core", "cash_flow", "operating", "fundamental"},
            required=True
        ),
        
        VariableDefinition(
            name="depreciation_amortization",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Depreciation and amortization",
            aliases={
                "excel": "D&A",
                "yfinance": "depreciation",
                "fmp": "depreciationAndAmortization"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="D&A should be positive")
            ],
            tags={"cash_flow", "operating", "non_cash", "depreciation"}
        )
    ])
    
    # Investing Cash Flow Variables
    variables.extend([
        VariableDefinition(
            name="investing_cash_flow",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Cash flow from investing activities",
            aliases={
                "excel": "Investing Cash Flow",
                "yfinance": "investingCashFlow",
                "fmp": "netCashUsedForInvestingActivities"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -100000, "max": 50000}, warning_only=True)
            ],
            tags={"cash_flow", "investing"}
        ),
        
        VariableDefinition(
            name="capital_expenditures",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Capital expenditures (CapEx)",
            aliases={
                "excel": "CapEx",
                "yfinance": "capitalExpenditures",
                "fmp": "capitalExpenditure",
                "alpha_vantage": "capitalExpenditures"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="CapEx should be positive (cash outflow)")
            ],
            tags={"core", "cash_flow", "investing", "capex", "fundamental"},
            required=True
        ),
        
        VariableDefinition(
            name="capex",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Capital expenditures (alias)",
            aliases={
                "excel": "CapEx",
                "fmp": "capex"
            },
            tags={"cash_flow", "investing", "capex", "alias"},
            derived_from=["capital_expenditures"]
        )
    ])
    
    # Financing Cash Flow Variables
    variables.extend([
        VariableDefinition(
            name="financing_cash_flow",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Cash flow from financing activities",
            aliases={
                "excel": "Financing Cash Flow",
                "yfinance": "financingCashFlow",
                "fmp": "netCashUsedProvidedByFinancingActivities"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -100000, "max": 100000}, warning_only=True)
            ],
            tags={"cash_flow", "financing"}
        ),
        
        VariableDefinition(
            name="dividends_paid",
            category=VariableCategory.CASH_FLOW,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Dividends paid to shareholders",
            aliases={
                "excel": "Dividends Paid",
                "yfinance": "dividendsPaid",
                "fmp": "dividendsPaid"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Dividends paid should be positive (cash outflow)")
            ],
            tags={"cash_flow", "financing", "dividends"}
        )
    ])
    
    # Free Cash Flow Variables
    variables.extend([
        VariableDefinition(
            name="free_cash_flow",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Free cash flow (Operating CF - CapEx)",
            calculation_method="Operating Cash Flow - Capital Expenditures",
            aliases={
                "excel": "FCF",
                "yfinance": "freeCashFlow",
                "fmp": "freeCashFlow"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -50000, "max": 150000}, warning_only=True)
            ],
            tags={"core", "calculated", "cash_flow", "fcf", "fundamental"},
            depends_on=["operating_cash_flow", "capital_expenditures"],
            required=True
        ),
        
        VariableDefinition(
            name="fcfe",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Free Cash Flow to Equity",
            long_description="Cash flow available to equity holders after all expenses, reinvestment, and debt payments",
            calculation_method="Net Income + Depreciation - CapEx - Change in Working Capital - Net Debt Payments",
            aliases={
                "excel": "FCFE",
                "fmp": "fcfe"
            },
            tags={"calculated", "cash_flow", "fcf", "fcfe", "valuation"},
            depends_on=["net_income", "depreciation_amortization", "capital_expenditures", "working_capital"]
        ),
        
        VariableDefinition(
            name="fcff",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Free Cash Flow to Firm",
            long_description="Cash flow available to all capital providers (debt and equity holders)",
            calculation_method="EBIT(1-Tax Rate) + Depreciation - CapEx - Change in Working Capital",
            aliases={
                "excel": "FCFF",
                "fmp": "fcff"
            },
            tags={"calculated", "cash_flow", "fcf", "fcff", "valuation"},
            depends_on=["ebit", "tax_expense", "depreciation_amortization", "capital_expenditures"]
        ),
        
        VariableDefinition(
            name="levered_fcf",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Levered Free Cash Flow (traditional FCF with debt effects)",
            calculation_method="Operating Cash Flow - Capital Expenditures",
            aliases={
                "excel": "Levered FCF",
                "fmp": "leveredFcf"
            },
            tags={"calculated", "cash_flow", "fcf", "levered", "lfcf"},
            depends_on=["operating_cash_flow", "capital_expenditures"]
        )
    ])
    
    return variables


def get_market_data_variables() -> List[VariableDefinition]:
    """Define all Market Data variables"""
    variables = []
    
    # Price Variables
    variables.extend([
        VariableDefinition(
            name="stock_price",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="Current stock price",
            aliases={
                "excel": "Stock Price",
                "yfinance": "regularMarketPrice",
                "fmp": "price"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Stock price must be positive")
            ],
            tags={"core", "market_data", "price", "real_time"}
        ),
        
        VariableDefinition(
            name="market_cap",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Market capitalization",
            calculation_method="Stock Price × Shares Outstanding",
            aliases={
                "excel": "Market Cap",
                "yfinance": "marketCap",
                "fmp": "marketCap"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Market cap must be positive")
            ],
            tags={"core", "market_data", "market_cap", "valuation"},
            depends_on=["stock_price", "shares_outstanding"],
            required=True
        ),
        
        VariableDefinition(
            name="enterprise_value",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Enterprise value",
            calculation_method="Market Cap + Total Debt - Cash",
            aliases={
                "excel": "Enterprise Value",
                "yfinance": "enterpriseValue",
                "fmp": "enterpriseValue"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Enterprise value should be positive")
            ],
            tags={"core", "market_data", "enterprise_value", "valuation"},
            depends_on=["market_cap", "total_debt", "cash_and_equivalents"]
        )
    ])
    
    # Share Variables
    variables.extend([
        VariableDefinition(
            name="shares_outstanding",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.SHARES,
            units=Units.SHARES_MILLIONS,
            description="Shares outstanding (from weighted average basic shares)",
            aliases={
                "excel": "Weighted Average Basic Shares Out",
                "yfinance": "sharesOutstanding",
                "fmp": "sharesOutstanding",
                "polygon": "weighted_shares_outstanding"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Shares outstanding must be positive")
            ],
            tags={"core", "market_data", "shares"},
            required=False  # Can be calculated if needed
        ),
        
        VariableDefinition(
            name="weighted_avg_shares",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.SHARES,
            units=Units.SHARES_MILLIONS,
            description="Weighted average shares outstanding",
            aliases={
                "excel": "Weighted Avg Shares",
                "yfinance": "weightedAverageShsOut",
                "fmp": "weightedAverageShsOut"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Weighted average shares must be positive")
            ],
            tags={"market_data", "shares", "weighted"}
        ),
        
        VariableDefinition(
            name="float_shares",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.SHARES,
            units=Units.SHARES_MILLIONS,
            description="Free float shares",
            aliases={
                "excel": "Float Shares",
                "yfinance": "floatShares",
                "fmp": "floatShares"
            },
            tags={"market_data", "shares", "float"}
        )
    ])
    
    # Technical Indicators
    variables.extend([
        VariableDefinition(
            name="beta",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Beta (systematic risk measure)",
            aliases={
                "excel": "Beta",
                "yfinance": "beta",
                "fmp": "beta"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -3.0, "max": 5.0}, warning_only=True)
            ],
            tags={"market_data", "risk", "beta", "systematic"}
        ),
        
        VariableDefinition(
            name="fifty_two_week_high",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="52-week high price",
            aliases={
                "excel": "52W High",
                "yfinance": "fiftyTwoWeekHigh",
                "fmp": "fiftyTwoWeekHigh"
            },
            validation_rules=[
                ValidationRule("positive", error_message="52-week high must be positive")
            ],
            tags={"market_data", "price", "historical", "high"}
        ),
        
        VariableDefinition(
            name="fifty_two_week_low",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="52-week low price",
            aliases={
                "excel": "52W Low",
                "yfinance": "fiftyTwoWeekLow",
                "fmp": "fiftyTwoWeekLow"
            },
            validation_rules=[
                ValidationRule("positive", error_message="52-week low must be positive")
            ],
            tags={"market_data", "price", "historical", "low"}
        )
    ])
    
    # Dividend Variables
    variables.extend([
        VariableDefinition(
            name="dividend_yield",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Dividend yield (as decimal)",
            aliases={
                "excel": "Dividend Yield",
                "yfinance": "dividendYield",
                "fmp": "dividendYield"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": 0.0, "max": 0.25})
            ],
            tags={"market_data", "dividend", "yield"}
        ),
        
        VariableDefinition(
            name="dividend_per_share",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="Dividend per share",
            aliases={
                "excel": "DPS",
                "yfinance": "dividendRate",
                "fmp": "dividendPerShare"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Dividend per share cannot be negative")
            ],
            tags={"market_data", "dividend", "per_share"}
        )
    ])
    
    return variables


def get_ratio_variables() -> List[VariableDefinition]:
    """Define all Financial Ratio variables"""
    variables = []
    
    # Valuation Ratios
    variables.extend([
        VariableDefinition(
            name="pe_ratio",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Price-to-earnings ratio",
            calculation_method="Stock Price / Earnings Per Share",
            aliases={
                "excel": "P/E Ratio",
                "yfinance": "forwardPE",
                "fmp": "peRatio"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": 0, "max": 1000}, warning_only=True)
            ],
            tags={"core", "ratios", "valuation", "pe"},
            depends_on=["stock_price", "earnings_per_share"]
        ),
        
        VariableDefinition(
            name="pb_ratio",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Price-to-book ratio",
            calculation_method="Market Cap / Book Value",
            aliases={
                "excel": "P/B Ratio",
                "yfinance": "priceToBook",
                "fmp": "pbRatio"
            },
            validation_rules=[
                ValidationRule("positive", error_message="P/B ratio should be positive")
            ],
            tags={"core", "ratios", "valuation", "pb"},
            depends_on=["market_cap", "book_value"]
        ),
        
        VariableDefinition(
            name="ps_ratio",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Price-to-sales ratio",
            calculation_method="Market Cap / Revenue",
            aliases={
                "excel": "P/S Ratio",
                "yfinance": "priceToSalesTrailing12Months",
                "fmp": "psRatio"
            },
            validation_rules=[
                ValidationRule("positive", error_message="P/S ratio should be positive")
            ],
            tags={"ratios", "valuation", "ps"},
            depends_on=["market_cap", "revenue"]
        ),
        
        VariableDefinition(
            name="ev_revenue",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Enterprise Value / Revenue",
            calculation_method="Enterprise Value / Revenue",
            aliases={
                "excel": "EV/Revenue",
                "fmp": "enterpriseValueMultiple"
            },
            validation_rules=[
                ValidationRule("positive", error_message="EV/Revenue should be positive")
            ],
            tags={"ratios", "valuation", "ev"},
            depends_on=["enterprise_value", "revenue"]
        ),
        
        VariableDefinition(
            name="ev_ebitda",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Enterprise Value / EBITDA",
            calculation_method="Enterprise Value / EBITDA",
            aliases={
                "excel": "EV/EBITDA",
                "yfinance": "enterpriseToEbitda",
                "fmp": "evEbitda"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": 0, "max": 100}, warning_only=True)
            ],
            tags={"core", "ratios", "valuation", "ev", "ebitda"},
            depends_on=["enterprise_value", "ebitda"]
        ),
        
        VariableDefinition(
            name="peg_ratio",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Price/Earnings to Growth ratio",
            aliases={
                "excel": "PEG Ratio",
                "yfinance": "pegRatio",
                "fmp": "pegRatio"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": 0, "max": 10}, warning_only=True)
            ],
            tags={"ratios", "valuation", "peg", "growth"}
        )
    ])
    
    # Profitability Ratios
    variables.extend([
        VariableDefinition(
            name="roe",
            category=VariableCategory.RATIOS,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Return on Equity",
            calculation_method="Net Income / Shareholders Equity",
            aliases={
                "excel": "ROE",
                "yfinance": "returnOnEquity",
                "fmp": "roe"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -1.0, "max": 2.0}, warning_only=True)
            ],
            tags={"core", "ratios", "profitability", "roe", "return"},
            depends_on=["net_income", "shareholders_equity"]
        ),
        
        VariableDefinition(
            name="roa",
            category=VariableCategory.RATIOS,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Return on Assets",
            calculation_method="Net Income / Total Assets",
            aliases={
                "excel": "ROA",
                "yfinance": "returnOnAssets",
                "fmp": "returnOnAssets"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -0.5, "max": 0.5}, warning_only=True)
            ],
            tags={"core", "ratios", "profitability", "roa", "return"},
            depends_on=["net_income", "total_assets"]
        ),
        
        VariableDefinition(
            name="roic",
            category=VariableCategory.RATIOS,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Return on Invested Capital",
            calculation_method="EBIT(1-Tax Rate) / Invested Capital",
            aliases={
                "excel": "ROIC",
                "fmp": "roic"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -0.5, "max": 1.0}, warning_only=True)
            ],
            tags={"core", "ratios", "profitability", "roic", "return"},
            depends_on=["ebit", "tax_expense", "total_assets", "current_liabilities"]
        ),
        
        VariableDefinition(
            name="gross_margin",
            category=VariableCategory.RATIOS,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Gross profit margin",
            calculation_method="Gross Profit / Revenue",
            aliases={
                "excel": "Gross Margin",
                "yfinance": "grossMargins",
                "fmp": "grossProfitMargin"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": -0.5, "max": 1.0})
            ],
            tags={"ratios", "profitability", "margin", "gross"},
            depends_on=["gross_profit", "revenue"]
        ),
        
        VariableDefinition(
            name="operating_margin",
            category=VariableCategory.RATIOS,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Operating profit margin",
            calculation_method="Operating Income / Revenue",
            aliases={
                "excel": "Operating Margin",
                "yfinance": "operatingMargins",
                "fmp": "operatingIncomeMargin"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": -1.0, "max": 1.0})
            ],
            tags={"ratios", "profitability", "margin", "operating"},
            depends_on=["operating_income", "revenue"]
        ),
        
        VariableDefinition(
            name="net_margin",
            category=VariableCategory.RATIOS,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Net profit margin",
            calculation_method="Net Income / Revenue",
            aliases={
                "excel": "Net Margin",
                "yfinance": "profitMargins",
                "fmp": "netIncomeMargin"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": -1.0, "max": 1.0})
            ],
            tags={"ratios", "profitability", "margin", "net"},
            depends_on=["net_income", "revenue"]
        )
    ])
    
    # Liquidity Ratios
    variables.extend([
        VariableDefinition(
            name="current_ratio",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Current ratio",
            calculation_method="Current Assets / Current Liabilities",
            aliases={
                "excel": "Current Ratio",
                "fmp": "currentRatio"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Current ratio should be positive")
            ],
            tags={"ratios", "liquidity", "current"},
            depends_on=["current_assets", "current_liabilities"]
        ),
        
        VariableDefinition(
            name="quick_ratio",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Quick ratio (acid test)",
            calculation_method="(Current Assets - Inventory) / Current Liabilities",
            aliases={
                "excel": "Quick Ratio",
                "fmp": "quickRatio"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="Quick ratio should be non-negative")
            ],
            tags={"ratios", "liquidity", "quick"},
            depends_on=["current_assets", "inventory", "current_liabilities"]
        )
    ])
    
    # Leverage Ratios
    variables.extend([
        VariableDefinition(
            name="debt_to_equity",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Debt-to-equity ratio",
            calculation_method="Total Debt / Shareholders Equity",
            aliases={
                "excel": "D/E Ratio",
                "fmp": "debtToEquityRatio"
            },
            validation_rules=[
                ValidationRule("non_negative", error_message="D/E ratio should be non-negative")
            ],
            tags={"ratios", "leverage", "debt"},
            depends_on=["total_debt", "shareholders_equity"]
        ),
        
        VariableDefinition(
            name="debt_to_assets",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Debt-to-assets ratio",
            calculation_method="Total Debt / Total Assets",
            aliases={
                "excel": "Debt to Assets",
                "fmp": "debtToAssetsRatio"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": 0.0, "max": 1.0})
            ],
            tags={"ratios", "leverage", "debt"},
            depends_on=["total_debt", "total_assets"]
        )
    ])
    
    return variables


def get_dcf_variables() -> List[VariableDefinition]:
    """Define DCF-specific variables"""
    variables = []
    
    variables.extend([
        VariableDefinition(
            name="wacc",
            category=VariableCategory.CALCULATED,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Weighted Average Cost of Capital",
            long_description="Blended cost of debt and equity financing weighted by capital structure",
            calculation_method="(E/V * Re) + ((D/V * Rd) * (1 - Tax Rate))",
            aliases={
                "excel": "WACC",
                "fmp": "wacc"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": 0.01, "max": 0.50})
            ],
            tags={"dcf", "calculated", "wacc", "discount_rate", "valuation"}
        ),
        
        VariableDefinition(
            name="terminal_growth_rate",
            category=VariableCategory.CALCULATED,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Terminal growth rate for DCF",
            aliases={
                "excel": "Terminal Growth Rate",
                "fmp": "terminalGrowthRate"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": 0.0, "max": 0.10})
            ],
            tags={"dcf", "calculated", "terminal", "growth", "valuation"}
        ),
        
        VariableDefinition(
            name="terminal_value",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.MILLIONS_USD,
            description="Terminal value in DCF model",
            aliases={
                "excel": "Terminal Value",
                "fmp": "terminalValue"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Terminal value should be positive")
            ],
            tags={"dcf", "calculated", "terminal", "valuation"}
        ),
        
        VariableDefinition(
            name="risk_free_rate",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Risk-free interest rate",
            aliases={
                "excel": "Risk Free Rate",
                "fmp": "riskFreeRate"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": 0.0, "max": 0.15})
            ],
            tags={"dcf", "market_data", "risk_free", "rate"}
        ),
        
        VariableDefinition(
            name="market_risk_premium",
            category=VariableCategory.MARKET_DATA,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Market risk premium",
            aliases={
                "excel": "Market Risk Premium",
                "fmp": "marketRiskPremium"
            },
            validation_rules=[
                ValidationRule("percentage_range", parameters={"min": 0.0, "max": 0.20})
            ],
            tags={"dcf", "market_data", "risk_premium"}
        )
    ])
    
    return variables


def get_per_share_variables() -> List[VariableDefinition]:
    """Define per-share metrics"""
    variables = []
    
    variables.extend([
        VariableDefinition(
            name="book_value_per_share",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="Book value per share",
            calculation_method="Book Value / Shares Outstanding",
            aliases={
                "excel": "BVPS",
                "yfinance": "bookValue",
                "fmp": "bookValuePerShare"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -100, "max": 1000}, warning_only=True)
            ],
            tags={"calculated", "per_share", "book_value", "bvps"},
            depends_on=["book_value", "shares_outstanding"]
        ),
        
        VariableDefinition(
            name="tangible_book_value_per_share",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="Tangible book value per share",
            calculation_method="Tangible Book Value / Shares Outstanding",
            aliases={
                "excel": "TBVPS",
                "fmp": "tangibleBookValuePerShare"
            },
            tags={"calculated", "per_share", "tangible", "book_value"},
            depends_on=["tangible_book_value", "shares_outstanding"]
        ),
        
        VariableDefinition(
            name="sales_per_share",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="Sales per share",
            calculation_method="Revenue / Shares Outstanding",
            aliases={
                "excel": "SPS",
                "fmp": "salesPerShare"
            },
            tags={"calculated", "per_share", "sales"},
            depends_on=["revenue", "shares_outstanding"]
        ),
        
        VariableDefinition(
            name="cash_per_share",
            category=VariableCategory.CALCULATED,
            data_type=DataType.CURRENCY,
            units=Units.DOLLARS,
            description="Cash per share",
            calculation_method="Cash and Cash Equivalents / Shares Outstanding",
            aliases={
                "excel": "Cash Per Share",
                "fmp": "cashPerShare"
            },
            tags={"calculated", "per_share", "cash"},
            depends_on=["cash_and_equivalents", "shares_outstanding"]
        )
    ])
    
    return variables


def get_efficiency_variables() -> List[VariableDefinition]:
    """Define efficiency and turnover ratios"""
    variables = []
    
    variables.extend([
        VariableDefinition(
            name="asset_turnover",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Asset turnover ratio",
            calculation_method="Revenue / Average Total Assets",
            aliases={
                "excel": "Asset Turnover",
                "fmp": "assetTurnover"
            },
            validation_rules=[
                ValidationRule("positive", error_message="Asset turnover should be positive")
            ],
            tags={"ratios", "efficiency", "turnover", "assets"},
            depends_on=["revenue", "total_assets"]
        ),
        
        VariableDefinition(
            name="receivables_turnover",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Receivables turnover ratio",
            calculation_method="Revenue / Average Accounts Receivable",
            aliases={
                "excel": "Receivables Turnover",
                "fmp": "receivablesTurnover"
            },
            tags={"ratios", "efficiency", "turnover", "receivables"},
            depends_on=["revenue", "accounts_receivable"]
        ),
        
        VariableDefinition(
            name="inventory_turnover",
            category=VariableCategory.RATIOS,
            data_type=DataType.FLOAT,
            units=Units.RATIO,
            description="Inventory turnover ratio",
            calculation_method="Cost of Revenue / Average Inventory",
            aliases={
                "excel": "Inventory Turnover",
                "fmp": "inventoryTurnover"
            },
            tags={"ratios", "efficiency", "turnover", "inventory"},
            depends_on=["cost_of_revenue", "inventory"]
        )
    ])
    
    return variables


def get_growth_variables() -> List[VariableDefinition]:
    """Define growth rate variables"""
    variables = []
    
    variables.extend([
        VariableDefinition(
            name="revenue_growth_rate",
            category=VariableCategory.CALCULATED,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Revenue growth rate (year-over-year)",
            aliases={
                "excel": "Revenue Growth",
                "fmp": "revenueGrowth"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -0.9, "max": 5.0}, warning_only=True)
            ],
            tags={"calculated", "growth", "revenue"}
        ),
        
        VariableDefinition(
            name="earnings_growth_rate",
            category=VariableCategory.CALCULATED,
            data_type=DataType.PERCENTAGE,
            units=Units.PERCENTAGE,
            description="Earnings growth rate (year-over-year)",
            aliases={
                "excel": "Earnings Growth",
                "fmp": "earningsGrowth"
            },
            validation_rules=[
                ValidationRule("range", parameters={"min": -5.0, "max": 10.0}, warning_only=True)
            ],
            tags={"calculated", "growth", "earnings"}
        )
    ])
    
    return variables


def get_standard_variables() -> List[VariableDefinition]:
    """
    Get all standard financial variables
    
    Returns:
        List of all VariableDefinition objects for standard financial variables
    """
    all_variables = []
    
    # Combine all variable categories
    all_variables.extend(get_income_statement_variables())
    all_variables.extend(get_balance_sheet_variables())
    all_variables.extend(get_cash_flow_variables())
    all_variables.extend(get_market_data_variables())
    all_variables.extend(get_ratio_variables())
    all_variables.extend(get_dcf_variables())
    all_variables.extend(get_per_share_variables())
    all_variables.extend(get_efficiency_variables())
    all_variables.extend(get_growth_variables())
    
    return all_variables


def register_all_variables(registry: FinancialVariableRegistry) -> Dict[str, Any]:
    """
    Register all standard variables with the registry
    
    Args:
        registry: The FinancialVariableRegistry instance
        
    Returns:
        Dictionary with registration statistics
    """
    variables = get_standard_variables()
    
    success_count = 0
    error_count = 0
    errors = []
    
    for variable in variables:
        try:
            if registry.register_variable(variable):
                success_count += 1
            else:
                error_count += 1
                errors.append(f"Variable {variable.name} already exists")
        except Exception as e:
            error_count += 1
            errors.append(f"Error registering {variable.name}: {str(e)}")
    
    stats = {
        "total_attempted": len(variables),
        "successful": success_count,
        "errors": error_count,
        "error_messages": errors,
        "registry_stats": registry.get_statistics()
    }
    
    return stats


def get_variables_by_statement_type(statement_type: str) -> List[VariableDefinition]:
    """
    Get variables for a specific financial statement type
    
    Args:
        statement_type: "income_statement", "balance_sheet", "cash_flow", "market_data", "ratios"
        
    Returns:
        List of variables for the specified statement type
    """
    mapping = {
        "income_statement": get_income_statement_variables,
        "balance_sheet": get_balance_sheet_variables, 
        "cash_flow": get_cash_flow_variables,
        "market_data": get_market_data_variables,
        "ratios": get_ratio_variables,
        "dcf": get_dcf_variables,
        "per_share": get_per_share_variables,
        "efficiency": get_efficiency_variables,
        "growth": get_growth_variables
    }
    
    if statement_type not in mapping:
        raise ValueError(f"Unknown statement type: {statement_type}. Available: {list(mapping.keys())}")
    
    return mapping[statement_type]()


def get_core_variables() -> List[VariableDefinition]:
    """
    Get only the core/essential financial variables marked with 'core' tag
    
    Returns:
        List of core variables
    """
    all_variables = get_standard_variables()
    return [var for var in all_variables if "core" in var.tags]


def get_variable_summary() -> Dict[str, Any]:
    """
    Get summary statistics of all standard variables
    
    Returns:
        Dictionary with variable summary statistics
    """
    variables = get_standard_variables()
    
    category_counts = {}
    tag_counts = {}
    data_type_counts = {}
    unit_counts = {}
    source_alias_counts = {}
    
    for var in variables:
        # Count by category
        category_counts[var.category.value] = category_counts.get(var.category.value, 0) + 1
        
        # Count by data type
        data_type_counts[var.data_type.value] = data_type_counts.get(var.data_type.value, 0) + 1
        
        # Count by units
        unit_counts[var.units.value] = unit_counts.get(var.units.value, 0) + 1
        
        # Count tags
        for tag in var.tags:
            tag_counts[tag] = tag_counts.get(tag, 0) + 1
        
        # Count source aliases
        for source in var.aliases.keys():
            source_alias_counts[source] = source_alias_counts.get(source, 0) + 1
    
    return {
        "total_variables": len(variables),
        "categories": category_counts,
        "data_types": data_type_counts,
        "units": unit_counts,
        "top_tags": dict(sorted(tag_counts.items(), key=lambda x: x[1], reverse=True)[:10]),
        "sources_with_aliases": source_alias_counts,
        "core_variables_count": len([v for v in variables if "core" in v.tags]),
        "required_variables_count": len([v for v in variables if v.required]),
        "variables_with_validation": len([v for v in variables if v.validation_rules])
    }


# Export the main functions for easy import
__all__ = [
    'get_standard_variables',
    'register_all_variables', 
    'get_variables_by_statement_type',
    'get_core_variables',
    'get_variable_summary'
]