"""
Real-time User Session Monitoring System

This module provides comprehensive monitoring capabilities for user sessions,
including real-time metrics collection, session replay, and alerting.
"""

import asyncio
import json
import time
import threading
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass, asdict
from enum import Enum
import logging
from pathlib import Path
import sqlite3
from contextlib import contextmanager
import websockets
import psutil
import queue

try:
    import aiohttp
    from aiohttp import web
    AIOHTTP_AVAILABLE = True
except ImportError:
    AIOHTTP_AVAILABLE = False


class AlertLevel(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class SessionMetric:
    """Individual session metric data point."""
    timestamp: datetime
    session_id: str
    metric_type: str
    value: float
    metadata: Dict[str, Any]


@dataclass
class Alert:
    """Alert generated by monitoring system."""
    alert_id: str
    level: AlertLevel
    title: str
    description: str
    timestamp: datetime
    session_id: Optional[str] = None
    resolved: bool = False
    resolution_time: Optional[datetime] = None


class MonitoringSystem:
    """
    Real-time monitoring system for user sessions and application performance.

    Features:
    - Real-time metrics collection
    - Session recording and replay
    - Alert generation and management
    - Performance trend analysis
    - WebSocket-based live updates
    """

    def __init__(self, db_path: str = "monitoring.db",
                 metrics_retention_days: int = 30,
                 alert_thresholds: Optional[Dict[str, float]] = None):
        self.db_path = db_path
        self.metrics_retention_days = metrics_retention_days
        self.alert_thresholds = alert_thresholds or self._get_default_thresholds()

        self.logger = self._setup_logging()
        self.metrics_queue = queue.Queue()
        self.alerts_queue = queue.Queue()
        self.active_sessions = {}
        self.websocket_clients = set()

        self._initialize_database()
        self._start_background_workers()

    def _setup_logging(self) -> logging.Logger:
        """Set up logging for monitoring system."""
        logger = logging.getLogger("monitoring_system")
        logger.setLevel(logging.INFO)

        if not logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter(
                '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            )
            handler.setFormatter(formatter)
            logger.addHandler(handler)

        return logger

    def _get_default_thresholds(self) -> Dict[str, float]:
        """Get default alert thresholds."""
        return {
            "page_load_time": 10.0,  # seconds
            "memory_usage_mb": 1000.0,  # MB
            "cpu_usage_percent": 85.0,  # %
            "error_rate_percent": 5.0,  # %
            "response_time_ms": 5000.0,  # milliseconds
        }

    def _initialize_database(self):
        """Initialize SQLite database for storing metrics and alerts."""
        with sqlite3.connect(self.db_path) as conn:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS session_metrics (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp TEXT NOT NULL,
                    session_id TEXT NOT NULL,
                    metric_type TEXT NOT NULL,
                    value REAL NOT NULL,
                    metadata TEXT
                );

                CREATE TABLE IF NOT EXISTS alerts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    alert_id TEXT UNIQUE NOT NULL,
                    level TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    timestamp TEXT NOT NULL,
                    session_id TEXT,
                    resolved INTEGER DEFAULT 0,
                    resolution_time TEXT
                );

                CREATE TABLE IF NOT EXISTS sessions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    session_id TEXT UNIQUE NOT NULL,
                    start_time TEXT NOT NULL,
                    end_time TEXT,
                    user_agent TEXT,
                    ip_address TEXT,
                    session_data TEXT
                );

                CREATE INDEX IF NOT EXISTS idx_metrics_session_time
                    ON session_metrics(session_id, timestamp);
                CREATE INDEX IF NOT EXISTS idx_alerts_timestamp
                    ON alerts(timestamp);
            """)

    def _start_background_workers(self):
        """Start background worker threads."""
        # Metrics processor thread
        metrics_thread = threading.Thread(target=self._process_metrics_worker, daemon=True)
        metrics_thread.start()

        # Alerts processor thread
        alerts_thread = threading.Thread(target=self._process_alerts_worker, daemon=True)
        alerts_thread.start()

        # Cleanup thread
        cleanup_thread = threading.Thread(target=self._cleanup_worker, daemon=True)
        cleanup_thread.start()

    def start_session(self, session_id: str, metadata: Dict[str, Any] = None) -> None:
        """Start monitoring a new user session."""
        session_data = {
            "start_time": datetime.now(),
            "metadata": metadata or {},
            "metrics_count": 0,
            "last_activity": datetime.now()
        }

        self.active_sessions[session_id] = session_data

        # Store in database
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("""
                INSERT OR REPLACE INTO sessions
                (session_id, start_time, user_agent, ip_address, session_data)
                VALUES (?, ?, ?, ?, ?)
            """, (
                session_id,
                session_data["start_time"].isoformat(),
                (metadata or {}).get("user_agent", ""),
                (metadata or {}).get("ip_address", ""),
                json.dumps(metadata or {})
            ))

        self.logger.info(f"Started monitoring session: {session_id}")

    def end_session(self, session_id: str) -> None:
        """End monitoring for a user session."""
        if session_id in self.active_sessions:
            session_data = self.active_sessions[session_id]
            end_time = datetime.now()

            # Update database
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    UPDATE sessions SET end_time = ? WHERE session_id = ?
                """, (end_time.isoformat(), session_id))

            del self.active_sessions[session_id]
            self.logger.info(f"Ended monitoring session: {session_id}")

    def record_metric(self, session_id: str, metric_type: str,
                     value: float, metadata: Dict[str, Any] = None) -> None:
        """Record a metric for a session."""
        metric = SessionMetric(
            timestamp=datetime.now(),
            session_id=session_id,
            metric_type=metric_type,
            value=value,
            metadata=metadata or {}
        )

        self.metrics_queue.put(metric)

        # Update session activity
        if session_id in self.active_sessions:
            self.active_sessions[session_id]["last_activity"] = datetime.now()
            self.active_sessions[session_id]["metrics_count"] += 1

    def _process_metrics_worker(self):
        """Background worker to process metrics queue."""
        while True:
            try:
                # Process batch of metrics
                metrics_batch = []

                # Collect metrics with timeout
                try:
                    metric = self.metrics_queue.get(timeout=5.0)
                    metrics_batch.append(metric)

                    # Collect additional metrics if available (up to 100)
                    while len(metrics_batch) < 100:
                        try:
                            metric = self.metrics_queue.get_nowait()
                            metrics_batch.append(metric)
                        except queue.Empty:
                            break

                except queue.Empty:
                    continue

                # Store metrics in database
                with sqlite3.connect(self.db_path) as conn:
                    conn.executemany("""
                        INSERT INTO session_metrics
                        (timestamp, session_id, metric_type, value, metadata)
                        VALUES (?, ?, ?, ?, ?)
                    """, [
                        (m.timestamp.isoformat(), m.session_id, m.metric_type,
                         m.value, json.dumps(m.metadata))
                        for m in metrics_batch
                    ])

                # Check for alerts
                for metric in metrics_batch:
                    self._check_metric_for_alerts(metric)

                # Send real-time updates to WebSocket clients
                if self.websocket_clients:
                    update_data = {
                        "type": "metrics_update",
                        "metrics": [asdict(m) for m in metrics_batch]
                    }
                    asyncio.run_coroutine_threadsafe(
                        self._broadcast_to_websockets(update_data),
                        asyncio.get_event_loop()
                    )

            except Exception as e:
                self.logger.error(f"Error processing metrics: {e}")
                time.sleep(1)

    def _check_metric_for_alerts(self, metric: SessionMetric):
        """Check if a metric triggers any alerts."""
        threshold_key = metric.metric_type.lower()

        if threshold_key in self.alert_thresholds:
            threshold = self.alert_thresholds[threshold_key]

            if metric.value > threshold:
                alert = Alert(
                    alert_id=f"{metric.session_id}_{metric.metric_type}_{int(time.time())}",
                    level=AlertLevel.WARNING if metric.value < threshold * 1.5 else AlertLevel.ERROR,
                    title=f"High {metric.metric_type}",
                    description=f"{metric.metric_type} is {metric.value:.2f}, exceeding threshold of {threshold:.2f}",
                    timestamp=datetime.now(),
                    session_id=metric.session_id
                )

                self.alerts_queue.put(alert)

    def _process_alerts_worker(self):
        """Background worker to process alerts queue."""
        while True:
            try:
                alert = self.alerts_queue.get(timeout=10.0)

                # Store alert in database
                with sqlite3.connect(self.db_path) as conn:
                    conn.execute("""
                        INSERT OR IGNORE INTO alerts
                        (alert_id, level, title, description, timestamp, session_id)
                        VALUES (?, ?, ?, ?, ?, ?)
                    """, (
                        alert.alert_id, alert.level.value, alert.title,
                        alert.description, alert.timestamp.isoformat(),
                        alert.session_id
                    ))

                self.logger.warning(f"Alert generated: {alert.title} - {alert.description}")

                # Send alert to WebSocket clients
                if self.websocket_clients:
                    alert_data = {
                        "type": "alert",
                        "alert": asdict(alert)
                    }
                    asyncio.run_coroutine_threadsafe(
                        self._broadcast_to_websockets(alert_data),
                        asyncio.get_event_loop()
                    )

            except queue.Empty:
                continue
            except Exception as e:
                self.logger.error(f"Error processing alerts: {e}")
                time.sleep(1)

    def _cleanup_worker(self):
        """Background worker for periodic cleanup."""
        while True:
            try:
                time.sleep(3600)  # Run every hour

                # Clean up old metrics
                cutoff_date = datetime.now() - timedelta(days=self.metrics_retention_days)

                with sqlite3.connect(self.db_path) as conn:
                    conn.execute("""
                        DELETE FROM session_metrics
                        WHERE timestamp < ?
                    """, (cutoff_date.isoformat(),))

                    deleted = conn.total_changes
                    if deleted > 0:
                        self.logger.info(f"Cleaned up {deleted} old metric records")

                # Clean up inactive sessions
                inactive_cutoff = datetime.now() - timedelta(hours=24)
                inactive_sessions = [
                    sid for sid, data in self.active_sessions.items()
                    if data["last_activity"] < inactive_cutoff
                ]

                for session_id in inactive_sessions:
                    self.end_session(session_id)

            except Exception as e:
                self.logger.error(f"Error in cleanup worker: {e}")

    async def _broadcast_to_websockets(self, data: Dict[str, Any]):
        """Broadcast data to all connected WebSocket clients."""
        if not self.websocket_clients:
            return

        message = json.dumps(data, default=str)
        disconnected = set()

        for websocket in self.websocket_clients:
            try:
                await websocket.send(message)
            except:
                disconnected.add(websocket)

        # Clean up disconnected clients
        self.websocket_clients -= disconnected

    def get_session_metrics(self, session_id: str,
                          metric_types: Optional[List[str]] = None,
                          hours: int = 24) -> List[SessionMetric]:
        """Get metrics for a specific session."""
        start_time = datetime.now() - timedelta(hours=hours)

        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT timestamp, session_id, metric_type, value, metadata
                FROM session_metrics
                WHERE session_id = ? AND timestamp > ?
            """
            params = [session_id, start_time.isoformat()]

            if metric_types:
                placeholders = ','.join('?' * len(metric_types))
                query += f" AND metric_type IN ({placeholders})"
                params.extend(metric_types)

            query += " ORDER BY timestamp"

            cursor = conn.execute(query, params)

            metrics = []
            for row in cursor:
                metrics.append(SessionMetric(
                    timestamp=datetime.fromisoformat(row[0]),
                    session_id=row[1],
                    metric_type=row[2],
                    value=row[3],
                    metadata=json.loads(row[4] or '{}')
                ))

            return metrics

    def get_active_sessions(self) -> Dict[str, Dict[str, Any]]:
        """Get information about currently active sessions."""
        return {
            session_id: {
                "start_time": data["start_time"].isoformat(),
                "last_activity": data["last_activity"].isoformat(),
                "metrics_count": data["metrics_count"],
                "metadata": data["metadata"]
            }
            for session_id, data in self.active_sessions.items()
        }

    def get_recent_alerts(self, hours: int = 24,
                         level: Optional[AlertLevel] = None) -> List[Alert]:
        """Get recent alerts."""
        start_time = datetime.now() - timedelta(hours=hours)

        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT alert_id, level, title, description, timestamp,
                       session_id, resolved, resolution_time
                FROM alerts
                WHERE timestamp > ?
            """
            params = [start_time.isoformat()]

            if level:
                query += " AND level = ?"
                params.append(level.value)

            query += " ORDER BY timestamp DESC"

            cursor = conn.execute(query, params)

            alerts = []
            for row in cursor:
                alerts.append(Alert(
                    alert_id=row[0],
                    level=AlertLevel(row[1]),
                    title=row[2],
                    description=row[3],
                    timestamp=datetime.fromisoformat(row[4]),
                    session_id=row[5],
                    resolved=bool(row[6]),
                    resolution_time=datetime.fromisoformat(row[7]) if row[7] else None
                ))

            return alerts

    def generate_monitoring_report(self, hours: int = 24) -> Dict[str, Any]:
        """Generate comprehensive monitoring report."""
        start_time = datetime.now() - timedelta(hours=hours)

        with sqlite3.connect(self.db_path) as conn:
            # Session statistics
            session_stats = conn.execute("""
                SELECT COUNT(DISTINCT session_id) as total_sessions,
                       AVG(metrics_count) as avg_metrics_per_session
                FROM (
                    SELECT session_id, COUNT(*) as metrics_count
                    FROM session_metrics
                    WHERE timestamp > ?
                    GROUP BY session_id
                ) AS session_counts
            """, (start_time.isoformat(),)).fetchone()

            # Metric statistics
            metric_stats = conn.execute("""
                SELECT metric_type,
                       COUNT(*) as count,
                       AVG(value) as avg_value,
                       MIN(value) as min_value,
                       MAX(value) as max_value
                FROM session_metrics
                WHERE timestamp > ?
                GROUP BY metric_type
                ORDER BY count DESC
            """, (start_time.isoformat(),)).fetchall()

            # Alert statistics
            alert_stats = conn.execute("""
                SELECT level, COUNT(*) as count
                FROM alerts
                WHERE timestamp > ?
                GROUP BY level
            """, (start_time.isoformat(),)).fetchall()

        return {
            "report_period": f"Last {hours} hours",
            "generated_at": datetime.now().isoformat(),
            "session_statistics": {
                "total_sessions": session_stats[0] or 0,
                "average_metrics_per_session": session_stats[1] or 0,
                "active_sessions": len(self.active_sessions)
            },
            "metric_statistics": [
                {
                    "metric_type": row[0],
                    "count": row[1],
                    "average_value": row[2],
                    "min_value": row[3],
                    "max_value": row[4]
                }
                for row in metric_stats
            ],
            "alert_statistics": [
                {
                    "level": row[0],
                    "count": row[1]
                }
                for row in alert_stats
            ],
            "system_health": self._get_system_health()
        }

    def _get_system_health(self) -> Dict[str, Any]:
        """Get current system health metrics."""
        return {
            "cpu_usage_percent": psutil.cpu_percent(),
            "memory_usage_percent": psutil.virtual_memory().percent,
            "disk_usage_percent": psutil.disk_usage('.').percent,
            "active_monitoring_sessions": len(self.active_sessions),
            "metrics_queue_size": self.metrics_queue.qsize(),
            "alerts_queue_size": self.alerts_queue.qsize()
        }

    async def create_websocket_server(self, host: str = "localhost", port: int = 8765):
        """Create WebSocket server for real-time monitoring updates."""
        async def handle_client(websocket, path):
            self.websocket_clients.add(websocket)
            self.logger.info(f"WebSocket client connected: {websocket.remote_address}")

            try:
                # Send initial data
                initial_data = {
                    "type": "initial_data",
                    "active_sessions": self.get_active_sessions(),
                    "recent_alerts": [asdict(a) for a in self.get_recent_alerts(hours=1)],
                    "system_health": self._get_system_health()
                }
                await websocket.send(json.dumps(initial_data, default=str))

                # Keep connection alive
                await websocket.wait_closed()
            finally:
                self.websocket_clients.discard(websocket)
                self.logger.info(f"WebSocket client disconnected: {websocket.remote_address}")

        if not AIOHTTP_AVAILABLE:
            self.logger.warning("aiohttp not available, WebSocket server disabled")
            return

        start_server = websockets.serve(handle_client, host, port)
        self.logger.info(f"WebSocket monitoring server starting on ws://{host}:{port}")

        return start_server


# Example usage and integration
class MonitoringIntegration:
    """Integration class for using monitoring system with test framework."""

    def __init__(self, monitoring_system: MonitoringSystem):
        self.monitoring = monitoring_system
        self.current_session_id = None

    def start_test_session(self, test_name: str, metadata: Dict[str, Any] = None):
        """Start monitoring for a test session."""
        self.current_session_id = f"test_{test_name}_{int(time.time())}"

        session_metadata = {
            "test_name": test_name,
            "test_type": "user_acceptance",
            "start_time": datetime.now().isoformat(),
        }
        session_metadata.update(metadata or {})

        self.monitoring.start_session(self.current_session_id, session_metadata)
        return self.current_session_id

    def record_test_metric(self, metric_type: str, value: float, metadata: Dict[str, Any] = None):
        """Record a metric during test execution."""
        if self.current_session_id:
            self.monitoring.record_metric(self.current_session_id, metric_type, value, metadata)

    def end_test_session(self):
        """End the current test session."""
        if self.current_session_id:
            self.monitoring.end_session(self.current_session_id)
            self.current_session_id = None


async def main():
    """Example usage of the monitoring system."""
    monitoring = MonitoringSystem()

    # Start a sample session
    session_id = "demo_session_" + str(int(time.time()))
    monitoring.start_session(session_id, {"user_type": "demo", "browser": "chrome"})

    # Record some sample metrics
    monitoring.record_metric(session_id, "page_load_time", 2.5)
    monitoring.record_metric(session_id, "memory_usage_mb", 150.0)
    monitoring.record_metric(session_id, "cpu_usage_percent", 45.0)

    # Simulate high metric that triggers alert
    monitoring.record_metric(session_id, "page_load_time", 15.0)

    # Wait a bit for processing
    await asyncio.sleep(2)

    # Generate report
    report = monitoring.generate_monitoring_report(hours=1)
    print("Monitoring Report:")
    print(json.dumps(report, indent=2, default=str))

    # Start WebSocket server for real-time monitoring
    websocket_server = await monitoring.create_websocket_server()
    if websocket_server:
        print("WebSocket server started on ws://localhost:8765")
        await websocket_server

    monitoring.end_session(session_id)


if __name__ == "__main__":
    asyncio.run(main())